# change the title to match your repository, suite, etc.
title: "MDI Docs Template"

# do not change any other lines below
remote_theme: MiDataInt/just-the-docs
color_scheme: mdi
search_enabled: true
logo: "/assets/images/portal_blur_200px.png"

# only page files in the _docs directory will be used
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    docs:
      name: Documentation
