# edit the following title with the short name of your repository, e.g My Pipelines
title: "MDI Docs Template"

# edit the following link used for the upper right navigation
aux_links:
  "Go To GitHub":
    - "https://github.com/MiDataInt/mdi-documentation-template"

# do not change any other lines in this file
remote_theme: MiDataInt/just-the-docs
color_scheme: mdi
search_enabled: true
logo: "/assets/images/portal_blur_200px.png"

# only page files in the _docs directory will be used
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    docs:
      name: Documentation
